name: Build latest Debian images

on:
  push:
    branches: [master]
    # paths: ['debian/**']

env:
  OS: debian
  DOCKER_REPO: ilyes512/php73-fpm

jobs:
  build_latest_debian:
    name: Build latest Debian
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker registry
        uses: azure/docker-login@8d6f807dfe933ef49956873df1022dd03a761071
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build containers
        run: |
          docker build \
            --build-arg VCS_REF=`git rev-parse HEAD` \
            --build-arg VERSION=$OS-latest-builder \
            --tag $DOCKER_REPO:$OS-latest-builder \
            --target builder \
            ./$OS
          docker build \
            --build-arg VCS_REF=`git rev-parse HEAD` \
            --build-arg VERSION=$OS-latest-runtime \
            --tag $DOCKER_REPO:$OS-latest-runtime \
            --target runtime \
            ./$OS
      - name: Push containers
        run: |
          docker push $DOCKER_REPO:$OS-latest-builder
          docker push $DOCKER_REPO:$OS-latest-runtime
