name: Build tagged Debian images

on:
  push:
    tags: ['debian-*']

env:
  OS: debian
  DOCKER_REPO: ilyes512/php73-fpm

jobs:
  build_tagged_debian:
    name: Build tagged Debian
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker registry
        uses: azure/docker-login@8d6f807dfe933ef49956873df1022dd03a761071
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build containers
        run: |
          TAG=`echo $GITHUB_REF | cut -c11-`
          echo "\$TAG: $TAG"
          docker build --tag $DOCKER_REPO:$TAG-builder --target builder ./$OS
          docker build --tag $DOCKER_REPO:$TAG-runtime --target runtime ./$OS
      - name: Push containers
        run: |
          TAG=`echo $GITHUB_REF | cut -c11-`
          echo "\$TAG: $TAG"
          docker push $DOCKER_REPO:$TAG-builder
          docker push $DOCKER_REPO:$TAG-runtime
